title: Jonathan Ng | Operations Research Officer, AI/ML, Data Science
description: "US Army Operations Research & Systems Analysis (ORSA) officer with 10+ years Army Finance experience, applying quantitative modeling, enterprise decision analysis, AI/ML compute infrastructure to solve operational problems. Builder of on-premises, self-hosted AI, multi-GPU systems, and automated data pipelines."
show_downloads: no
theme: jekyll-theme-minimal
logo: images/JonNg5.jpg
